application: dwms
version: 2
runtime: python
api_version: 1

handlers:
#### ADMIN SETUP
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /admin(($)|(/.*))
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

#### STATIC FILES SETUP
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  expiration: "24h"
- url: /static
  static_dir: static/
  expiration: "24h"
  #static_files: static/\1
  #upload: static/(.*\.(js|css))

#### USER MANAGEMENT
- url: /users(($)|(/.*))
  #Match /users  and EndOfString OR /*
  script: users.py
  login: admin

#### DYNAMIC CONTENT
- url: /((m/)|(o/)|(t/)|(gmap)|(colors)|(legend)|(query)|(classify)|(ids.csv)|(o.png))/?.*
  script: main.py
- url: /
  script: main.py
- url: /proxy.py.*
  script: proxy.py
#### TASKS
- url: /tasks.*
  script: taskQueue.py
  login: admin
