# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDyMaps(wx.Frame):
#!XRCED:begin-block:xrcDyMaps.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDyMaps.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "DyMaps")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.ToolBar = xrc.XRCCTRL(self, "ToolBar")
        self.MainPanel = xrc.XRCCTRL(self, "MainPanel")
        self.dataFile = xrc.XRCCTRL(self, "dataFile")
        self.fileopenbutton = xrc.XRCCTRL(self, "fileopenbutton")
        self.varsChoice = xrc.XRCCTRL(self, "varsChoice")
        self.SourceProj = xrc.XRCCTRL(self, "SourceProj")
        self.TargerProj = xrc.XRCCTRL(self, "TargerProj")
        self.NameTextCtrl = xrc.XRCCTRL(self, "NameTextCtrl")
        self.SourceTextCtrl = xrc.XRCCTRL(self, "SourceTextCtrl")
        self.NotesTextCtrl = xrc.XRCCTRL(self, "NotesTextCtrl")
        self.scalesChoice = xrc.XRCCTRL(self, "scalesChoice")
        self.mapPanel = xrc.XRCCTRL(self, "mapPanel")
        self.cacheFile = xrc.XRCCTRL(self, "cacheFile")
        self.ButtonCache = xrc.XRCCTRL(self, "ButtonCache")
        self.cacheWarn = xrc.XRCCTRL(self, "cacheWarn")
        self.StatusTxt = xrc.XRCCTRL(self, "StatusTxt")
        self.ButtonSaveMS = xrc.XRCCTRL(self, "ButtonSaveMS")
        self.ButtonRender = xrc.XRCCTRL(self, "ButtonRender")
        self.ButtonUpload = xrc.XRCCTRL(self, "ButtonUpload")
        self.Close = xrc.XRCCTRL(self, "Close")
        self.ButtonSave = xrc.XRCCTRL(self, "ButtonSave")

        self.Bind(wx.EVT_TOOL, self.OnTool_ToolNew, id=xrc.XRCID('ToolNew'))
        self.Bind(wx.EVT_TOOL, self.OnTool_ToolOpen, id=xrc.XRCID('ToolOpen'))
        self.Bind(wx.EVT_TOOL, self.OnTool_ToolSave, id=xrc.XRCID('ToolSave'))
        self.Bind(wx.EVT_TOOL, self.OnTool_ToolSaveAs, id=xrc.XRCID('ToolSaveAs'))
        self.Bind(wx.EVT_TEXT, self.OnText_dataFile, self.dataFile)
        self.Bind(wx.EVT_BUTTON, self.OnButton_fileopenbutton, self.fileopenbutton)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_varsChoice, self.varsChoice)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_SourceProj, self.SourceProj)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_TargerProj, self.TargerProj)
        self.Bind(wx.EVT_TEXT, self.OnText_NameTextCtrl, self.NameTextCtrl)
        self.Bind(wx.EVT_TEXT, self.OnText_SourceTextCtrl, self.SourceTextCtrl)
        self.Bind(wx.EVT_TEXT, self.OnText_NotesTextCtrl, self.NotesTextCtrl)
        self.Bind(wx.EVT_CHOICE, self.OnChoice_scalesChoice, self.scalesChoice)
        self.Bind(wx.EVT_TEXT, self.OnText_cacheFile, self.cacheFile)
        self.Bind(wx.EVT_BUTTON, self.OnButton_ButtonCache, self.ButtonCache)
        self.Bind(wx.EVT_BUTTON, self.OnButton_ButtonSaveMS, self.ButtonSaveMS)
        self.Bind(wx.EVT_BUTTON, self.OnButton_ButtonRender, self.ButtonRender)
        self.Bind(wx.EVT_BUTTON, self.OnButton_ButtonUpload, self.ButtonUpload)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Close, self.Close)
        self.Bind(wx.EVT_BUTTON, self.OnButton_ButtonSave, self.ButtonSave)
        self.Bind(wx.EVT_SIZE, self.OnSize)
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_PAINT, self.OnPaint)

#!XRCED:begin-block:xrcDyMaps.OnTool_ToolNew
    def OnTool_ToolNew(self, evt):
        # Replace with event handler code
        print "OnTool_ToolNew()"
#!XRCED:end-block:xrcDyMaps.OnTool_ToolNew        

#!XRCED:begin-block:xrcDyMaps.OnTool_ToolOpen
    def OnTool_ToolOpen(self, evt):
        # Replace with event handler code
        print "OnTool_ToolOpen()"
#!XRCED:end-block:xrcDyMaps.OnTool_ToolOpen        

#!XRCED:begin-block:xrcDyMaps.OnTool_ToolSave
    def OnTool_ToolSave(self, evt):
        # Replace with event handler code
        print "OnTool_ToolSave()"
#!XRCED:end-block:xrcDyMaps.OnTool_ToolSave        

#!XRCED:begin-block:xrcDyMaps.OnTool_ToolSaveAs
    def OnTool_ToolSaveAs(self, evt):
        # Replace with event handler code
        print "OnTool_ToolSaveAs()"
#!XRCED:end-block:xrcDyMaps.OnTool_ToolSaveAs        

#!XRCED:begin-block:xrcDyMaps.OnText_dataFile
    def OnText_dataFile(self, evt):
        # Replace with event handler code
        print "OnText_dataFile()"
#!XRCED:end-block:xrcDyMaps.OnText_dataFile        

#!XRCED:begin-block:xrcDyMaps.OnButton_fileopenbutton
    def OnButton_fileopenbutton(self, evt):
        # Replace with event handler code
        print "OnButton_fileopenbutton()"
#!XRCED:end-block:xrcDyMaps.OnButton_fileopenbutton        

#!XRCED:begin-block:xrcDyMaps.OnChoice_varsChoice
    def OnChoice_varsChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_varsChoice()"
#!XRCED:end-block:xrcDyMaps.OnChoice_varsChoice        

#!XRCED:begin-block:xrcDyMaps.OnChoice_SourceProj
    def OnChoice_SourceProj(self, evt):
        # Replace with event handler code
        print "OnChoice_SourceProj()"
#!XRCED:end-block:xrcDyMaps.OnChoice_SourceProj        

#!XRCED:begin-block:xrcDyMaps.OnChoice_TargerProj
    def OnChoice_TargerProj(self, evt):
        # Replace with event handler code
        print "OnChoice_TargerProj()"
#!XRCED:end-block:xrcDyMaps.OnChoice_TargerProj        

#!XRCED:begin-block:xrcDyMaps.OnText_NameTextCtrl
    def OnText_NameTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_NameTextCtrl()"
#!XRCED:end-block:xrcDyMaps.OnText_NameTextCtrl        

#!XRCED:begin-block:xrcDyMaps.OnText_SourceTextCtrl
    def OnText_SourceTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_SourceTextCtrl()"
#!XRCED:end-block:xrcDyMaps.OnText_SourceTextCtrl        

#!XRCED:begin-block:xrcDyMaps.OnText_NotesTextCtrl
    def OnText_NotesTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_NotesTextCtrl()"
#!XRCED:end-block:xrcDyMaps.OnText_NotesTextCtrl        

#!XRCED:begin-block:xrcDyMaps.OnChoice_scalesChoice
    def OnChoice_scalesChoice(self, evt):
        # Replace with event handler code
        print "OnChoice_scalesChoice()"
#!XRCED:end-block:xrcDyMaps.OnChoice_scalesChoice        

#!XRCED:begin-block:xrcDyMaps.OnText_cacheFile
    def OnText_cacheFile(self, evt):
        # Replace with event handler code
        print "OnText_cacheFile()"
#!XRCED:end-block:xrcDyMaps.OnText_cacheFile        

#!XRCED:begin-block:xrcDyMaps.OnButton_ButtonCache
    def OnButton_ButtonCache(self, evt):
        # Replace with event handler code
        print "OnButton_ButtonCache()"
#!XRCED:end-block:xrcDyMaps.OnButton_ButtonCache        

#!XRCED:begin-block:xrcDyMaps.OnButton_ButtonSaveMS
    def OnButton_ButtonSaveMS(self, evt):
        # Replace with event handler code
        print "OnButton_ButtonSaveMS()"
#!XRCED:end-block:xrcDyMaps.OnButton_ButtonSaveMS        

#!XRCED:begin-block:xrcDyMaps.OnButton_ButtonRender
    def OnButton_ButtonRender(self, evt):
        # Replace with event handler code
        print "OnButton_ButtonRender()"
#!XRCED:end-block:xrcDyMaps.OnButton_ButtonRender        

#!XRCED:begin-block:xrcDyMaps.OnButton_ButtonUpload
    def OnButton_ButtonUpload(self, evt):
        # Replace with event handler code
        print "OnButton_ButtonUpload()"
#!XRCED:end-block:xrcDyMaps.OnButton_ButtonUpload        

#!XRCED:begin-block:xrcDyMaps.OnButton_Close
    def OnButton_Close(self, evt):
        # Replace with event handler code
        print "OnButton_Close()"
#!XRCED:end-block:xrcDyMaps.OnButton_Close        

#!XRCED:begin-block:xrcDyMaps.OnButton_ButtonSave
    def OnButton_ButtonSave(self, evt):
        # Replace with event handler code
        print "OnButton_ButtonSave()"
#!XRCED:end-block:xrcDyMaps.OnButton_ButtonSave        

#!XRCED:begin-block:xrcDyMaps.OnSize
    def OnSize(self, evt):
        # Replace with event handler code
        print "OnSize()"
#!XRCED:end-block:xrcDyMaps.OnSize        

#!XRCED:begin-block:xrcDyMaps.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcDyMaps.OnClose        

#!XRCED:begin-block:xrcDyMaps.OnPaint
    def OnPaint(self, evt):
        # Replace with event handler code
        print "OnPaint()"
#!XRCED:end-block:xrcDyMaps.OnPaint        


class xrcUploadTiles(wx.Dialog):
#!XRCED:begin-block:xrcUploadTiles.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcUploadTiles.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "UploadTiles")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.DATA = xrc.XRCCTRL(self, "DATA")
        self.DATAOPEN = xrc.XRCCTRL(self, "DATAOPEN")
        self.ServerTextCtrl = xrc.XRCCTRL(self, "ServerTextCtrl")
        self.UserTextCtrl = xrc.XRCCTRL(self, "UserTextCtrl")
        self.PasswdTextCtrl = xrc.XRCCTRL(self, "PasswdTextCtrl")
        self.TESTCONN = xrc.XRCCTRL(self, "TESTCONN")
        self.checkMap = xrc.XRCCTRL(self, "checkMap")
        self.checkIDS = xrc.XRCCTRL(self, "checkIDS")
        self.checkOverview = xrc.XRCCTRL(self, "checkOverview")
        self.checkTiles = xrc.XRCCTRL(self, "checkTiles")
        self.CloseButton = xrc.XRCCTRL(self, "CloseButton")
        self.UPLOAD = xrc.XRCCTRL(self, "UPLOAD")

        self.Bind(wx.EVT_TEXT, self.OnText_DATA, self.DATA)
        self.Bind(wx.EVT_BUTTON, self.OnButton_DATAOPEN, self.DATAOPEN)
        self.Bind(wx.EVT_TEXT, self.OnText_ServerTextCtrl, self.ServerTextCtrl)
        self.Bind(wx.EVT_TEXT, self.OnText_UserTextCtrl, self.UserTextCtrl)
        self.Bind(wx.EVT_TEXT, self.OnText_PasswdTextCtrl, self.PasswdTextCtrl)
        self.Bind(wx.EVT_BUTTON, self.OnButton_TESTCONN, self.TESTCONN)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_checkMap, self.checkMap)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_checkIDS, self.checkIDS)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_checkOverview, self.checkOverview)
        self.Bind(wx.EVT_CHECKBOX, self.OnCheckbox_checkTiles, self.checkTiles)
        self.Bind(wx.EVT_BUTTON, self.OnButton_CloseButton, self.CloseButton)
        self.Bind(wx.EVT_BUTTON, self.OnButton_UPLOAD, self.UPLOAD)

#!XRCED:begin-block:xrcUploadTiles.OnText_DATA
    def OnText_DATA(self, evt):
        # Replace with event handler code
        print "OnText_DATA()"
#!XRCED:end-block:xrcUploadTiles.OnText_DATA        

#!XRCED:begin-block:xrcUploadTiles.OnButton_DATAOPEN
    def OnButton_DATAOPEN(self, evt):
        # Replace with event handler code
        print "OnButton_DATAOPEN()"
#!XRCED:end-block:xrcUploadTiles.OnButton_DATAOPEN        

#!XRCED:begin-block:xrcUploadTiles.OnText_ServerTextCtrl
    def OnText_ServerTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_ServerTextCtrl()"
#!XRCED:end-block:xrcUploadTiles.OnText_ServerTextCtrl        

#!XRCED:begin-block:xrcUploadTiles.OnText_UserTextCtrl
    def OnText_UserTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_UserTextCtrl()"
#!XRCED:end-block:xrcUploadTiles.OnText_UserTextCtrl        

#!XRCED:begin-block:xrcUploadTiles.OnText_PasswdTextCtrl
    def OnText_PasswdTextCtrl(self, evt):
        # Replace with event handler code
        print "OnText_PasswdTextCtrl()"
#!XRCED:end-block:xrcUploadTiles.OnText_PasswdTextCtrl        

#!XRCED:begin-block:xrcUploadTiles.OnButton_TESTCONN
    def OnButton_TESTCONN(self, evt):
        # Replace with event handler code
        print "OnButton_TESTCONN()"
#!XRCED:end-block:xrcUploadTiles.OnButton_TESTCONN        

#!XRCED:begin-block:xrcUploadTiles.OnCheckbox_checkMap
    def OnCheckbox_checkMap(self, evt):
        # Replace with event handler code
        print "OnCheckbox_checkMap()"
#!XRCED:end-block:xrcUploadTiles.OnCheckbox_checkMap        

#!XRCED:begin-block:xrcUploadTiles.OnCheckbox_checkIDS
    def OnCheckbox_checkIDS(self, evt):
        # Replace with event handler code
        print "OnCheckbox_checkIDS()"
#!XRCED:end-block:xrcUploadTiles.OnCheckbox_checkIDS        

#!XRCED:begin-block:xrcUploadTiles.OnCheckbox_checkOverview
    def OnCheckbox_checkOverview(self, evt):
        # Replace with event handler code
        print "OnCheckbox_checkOverview()"
#!XRCED:end-block:xrcUploadTiles.OnCheckbox_checkOverview        

#!XRCED:begin-block:xrcUploadTiles.OnCheckbox_checkTiles
    def OnCheckbox_checkTiles(self, evt):
        # Replace with event handler code
        print "OnCheckbox_checkTiles()"
#!XRCED:end-block:xrcUploadTiles.OnCheckbox_checkTiles        

#!XRCED:begin-block:xrcUploadTiles.OnButton_CloseButton
    def OnButton_CloseButton(self, evt):
        # Replace with event handler code
        print "OnButton_CloseButton()"
#!XRCED:end-block:xrcUploadTiles.OnButton_CloseButton        

#!XRCED:begin-block:xrcUploadTiles.OnButton_UPLOAD
    def OnButton_UPLOAD(self, evt):
        # Replace with event handler code
        print "OnButton_UPLOAD()"
#!XRCED:end-block:xrcUploadTiles.OnButton_UPLOAD        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    DyMaps_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="DyMaps">
    <object class="wxToolBar" name="ToolBar">
      <object class="tool" name="ToolNew">
        <bitmap stock_id="wxART_NORMAL_FILE"/>
        <label>TOOL</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <object class="tool" name="ToolOpen">
        <bitmap stock_id="wxART_FILE_OPEN"/>
        <label>TOOL</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <object class="tool" name="ToolSave">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <label>TOOL</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <object class="tool" name="ToolSaveAs">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <label>TOOL</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel" name="MainPanel">
          <object class="wxBoxSizer">
            <orient>wxHORIZONTAL</orient>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxPanel">
                    <object class="wxStaticBoxSizer" name="mapSettingsSizer">
                      <object class="sizeritem">
                        <object class="wxPanel">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxHORIZONTAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>ShapeFile</label>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE</flag>
                                  <border>3</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="dataFile">
                                    <XRCED>
                                      <events>EVT_TEXT</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxALIGN_CENTRE</flag>
                                  <border>3</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxBitmapButton" name="fileopenbutton">
                                    <size>25,25</size>
                                    <bitmap stock_id="wxART_FILE_OPEN"/>
                                    <XRCED>
                                      <events>EVT_BUTTON</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <flag>wxALL|wxALIGN_CENTRE</flag>
                                  <border>3</border>
                                </object>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxHORIZONTAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>ID Variable</label>
                                  </object>
                                  <flag>wxALL|wxEXPAND|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL</flag>
                                  <border>5</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxChoice" name="varsChoice">
                                    <content>
                                      <item/>
                                    </content>
                                    <XRCED>
                                      <events>EVT_CHOICE</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                          </object>
                        </object>
                        <flag>wxALL|wxEXPAND</flag>
                      </object>
                      <label>[+] Map Settings</label>
                      <orient>wxVERTICAL</orient>
                    </object>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxPanel">
                    <object class="wxStaticBoxSizer">
                      <orient>wxVERTICAL</orient>
                      <object class="sizeritem">
                        <object class="wxPanel" name="ProjPanel">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxHORIZONTAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText" name="">
                                    <label>Source Projection: </label>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxChoice" name="SourceProj">
                                    <content>
                                      <item>'init=EPSG:2223'</item>
                                    </content>
                                    <XRCED>
                                      <events>EVT_CHOICE</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                </object>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxHORIZONTAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText" name="">
                                    <label>Target Projection: </label>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxChoice" name="TargerProj">
                                    <content>
                                      <item>Google: 'init=EPSG:900913'</item>
                                    </content>
                                    <selection>0</selection>
                                    <XRCED>
                                      <events>EVT_CHOICE</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                </object>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                          </object>
                        </object>
                        <flag>wxALL|wxEXPAND</flag>
                      </object>
                      <label>[+] Projection</label>
                    </object>
                    <hidden>1</hidden>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxPanel">
                    <object class="wxStaticBoxSizer">
                      <label>[+] Meta Data</label>
                      <orient>wxVERTICAL</orient>
                      <object class="sizeritem">
                        <object class="wxPanel" name="metaPanel">
                          <object class="wxBoxSizer">
                            <orient>wxVERTICAL</orient>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>TileSet Name</label>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="NameTextCtrl">
                                    <XRCED>
                                      <events>EVT_TEXT</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                                <orient>wxHORIZONTAL</orient>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <orient>wxHORIZONTAL</orient>
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>Source</label>
                                  </object>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="SourceTextCtrl">
                                    <XRCED>
                                      <events>EVT_TEXT</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                              </object>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                            <object class="sizeritem">
                              <object class="wxBoxSizer">
                                <object class="sizeritem">
                                  <object class="wxStaticText">
                                    <label>Notes</label>
                                    <style/>
                                  </object>
                                  <flag>wxALIGN_CENTRE</flag>
                                </object>
                                <object class="spacer">
                                  <size>15,0</size>
                                </object>
                                <object class="sizeritem">
                                  <object class="wxTextCtrl" name="NotesTextCtrl">
                                    <style>wxTE_MULTILINE</style>
                                    <XRCED>
                                      <events>EVT_TEXT</events>
                                      <assign_var>1</assign_var>
                                    </XRCED>
                                  </object>
                                  <option>1</option>
                                  <flag>wxALL|wxEXPAND</flag>
                                  <border>5</border>
                                </object>
                                <orient>wxHORIZONTAL</orient>
                              </object>
                              <option>1</option>
                              <flag>wxALL|wxEXPAND</flag>
                            </object>
                          </object>
                        </object>
                        <option>1</option>
                        <flag>wxALL|wxEXPAND</flag>
                      </object>
                    </object>
                  </object>
                  <option>1</option>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxPanel">
                    <object class="wxStaticBoxSizer">
                      <object class="sizeritem">
                        <object class="wxChoice" name="scalesChoice">
                          <size>300,-1</size>
                          <XRCED>
                            <events>EVT_CHOICE</events>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                      </object>
                      <label>[+] Tile Settings</label>
                      <orient>wxVERTICAL</orient>
                    </object>
                  </object>
                  <option>0</option>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
              </object>
              <flag>wxALL|wxEXPAND</flag>
            </object>
            <object class="sizeritem">
              <object class="wxStaticBoxSizer">
                <label>Map</label>
                <orient>wxVERTICAL</orient>
                <object class="spacer">
                  <size>256,0</size>
                </object>
                <object class="sizeritem">
                  <object class="wxPanel" name="mapPanel">
                    <size>256,256</size>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxALL|wxEXPAND|wxGROW</flag>
                </object>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND</flag>
              <border>3</border>
            </object>
          </object>
          <fg>#FFFFFF</fg>
          <bg>#FFFFFF</bg>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="TilesPanel">
          <object class="wxStaticBoxSizer">
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <object class="sizeritem">
                  <object class="wxStaticText">
                    <label>Tile Cache File</label>
                  </object>
                  <flag>wxALL</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxTextCtrl" name="cacheFile">
                    <XRCED>
                      <events>EVT_TEXT</events>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxLEFT|wxRIGHT</flag>
                  <border>6</border>
                </object>
                <object class="sizeritem">
                  <object class="wxBitmapButton" name="ButtonCache">
                    <size>25,25</size>
                    <bitmap stock_id="wxART_FOLDER_OPEN"/>
                    <XRCED>
                      <events>EVT_BUTTON</events>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <flag>wxLEFT|wxRIGHT</flag>
                </object>
                <orient>wxHORIZONTAL</orient>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND</flag>
            </object>
            <label>Render Output</label>
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Status:</label>
                      </object>
                      <flag>wxALL</flag>
                      <border>5</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxFlexGridSizer">
                        <object class="spacer">
                          <size>20,0</size>
                        </object>
                        <object class="sizeritem">
                          <object class="wxStaticBitmap" name="cacheWarn">
                            <size>20,20</size>
                            <bitmap stock_id="wxART_WARNING"/>
                            <XRCED>
                              <assign_var>1</assign_var>
                            </XRCED>
                          </object>
                          <flag>wxALL</flag>
                        </object>
                        <cols>1</cols>
                        <rows>2</rows>
                      </object>
                      <flag>wxALL|wxALIGN_CENTRE</flag>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                    <object class="sizeritem">
                      <object class="wxStaticText" name="StatusTxt">
                        <fg>#00ff00</fg>
                        <XRCED>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL</flag>
                      <border>5</border>
                    </object>
                  </object>
                </object>
                <orient>wxVERTICAL</orient>
                <object class="spacer">
                  <size>10,10</size>
                  <option>0</option>
                </object>
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="spacer">
                      <option>1</option>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="ButtonSaveMS">
                        <label>Save For TileServer</label>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                    </object>
                    <object class="spacer">
                      <option>1</option>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="ButtonRender">
                        <label>Render Tiles</label>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                    </object>
                    <object class="spacer">
                      <option>1</option>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="ButtonUpload">
                        <label>Upload Tiles</label>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                    </object>
                    <object class="spacer">
                      <option>1</option>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>6</border>
                </object>
              </object>
              <flag>wxALL|wxEXPAND</flag>
            </object>
          </object>
          <fg>#FFFFFF</fg>
          <bg>#FFFFFF</bg>
        </object>
        <flag>wxALL|wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="ButtonPanel">
          <object class="wxBoxSizer">
            <orient>wxHORIZONTAL</orient>
            <object class="sizeritem">
              <object class="wxButton" name="Close">
                <label>Close</label>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="spacer">
              <size>80,0</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="ButtonSave">
                <label>Save</label>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="spacer">
              <size>0,0</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="ButtonRenderOld">
                <label>Render</label>
                <hidden>1</hidden>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
          </object>
        </object>
        <flag>wxALL|wxALIGN_CENTRE</flag>
        <border>5</border>
      </object>
    </object>
    <title>Map Loader</title>
    <style>wxDEFAULT_FRAME_STYLE</style>
    <XRCED>
      <events>EVT_SIZE|EVT_CLOSE|EVT_PAINT</events>
    </XRCED>
  </object>
  <object class="wxDialog" name="UploadTiles">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxStaticBoxSizer">
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <label>Map Config</label>
                      </object>
                      <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                      <border>0</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="DATA">
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>6</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxBitmapButton" name="DATAOPEN">
                        <bitmap stock_id="wxART_FOLDER_OPEN"/>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <option>1</option>
                  <flag>wxALL|wxEXPAND</flag>
                </object>
                <label>Map Info</label>
                <orient>wxHORIZONTAL</orient>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="sizeritem">
              <object class="wxStaticBoxSizer">
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <size>70,-1</size>
                        <label>Server</label>
                        <style>wxALIGN_LEFT</style>
                      </object>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="ServerTextCtrl">
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <size>70,-1</size>
                        <label>Email</label>
                      </object>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="UserTextCtrl">
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxStaticText">
                        <size>70,-1</size>
                        <label>Password</label>
                      </object>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxTextCtrl" name="PasswdTextCtrl">
                        <style>wxTE_PASSWORD</style>
                        <XRCED>
                          <events>EVT_TEXT</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>1</option>
                      <flag>wxALL|wxEXPAND</flag>
                      <border>3</border>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
                <label>Connection</label>
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <orient>wxHORIZONTAL</orient>
                    <object class="spacer">
                      <option>1</option>
                      <flag>wxALL|wxEXPAND|wxGROW</flag>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="TESTCONN">
                        <label>Test Connection</label>
                        <style>wxNO_BORDER|wxNO_BORDER</style>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>0</option>
                      <flag>wxRIGHT|wxALIGN_RIGHT</flag>
                    </object>
                  </object>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="sizeritem">
              <object class="wxStaticBoxSizer">
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="sizeritem">
                      <object class="wxCheckBox" name="checkMap">
                        <label>Map Settings</label>
                        <checked>1</checked>
                        <XRCED>
                          <events>EVT_CHECKBOX</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                    </object>
                    <object class="sizeritem">
                      <object class="wxCheckBox" name="checkIDS">
                        <label>Unique IDs</label>
                        <checked>1</checked>
                        <XRCED>
                          <events>EVT_CHECKBOX</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <option>0</option>
                      <flag>wxLEFT|wxEXPAND</flag>
                      <border>20</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxCheckBox" name="checkOverview">
                        <label>Overview</label>
                        <checked>1</checked>
                        <XRCED>
                          <events>EVT_CHECKBOX</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                      <flag>wxLEFT</flag>
                      <border>20</border>
                    </object>
                    <object class="sizeritem">
                      <object class="wxCheckBox" name="checkTiles">
                        <label>Tiles</label>
                        <checked>1</checked>
                        <XRCED>
                          <events>EVT_CHECKBOX</events>
                          <assign_var>1</assign_var>
                        </XRCED>
                      </object>
                    </object>
                    <orient>wxVERTICAL</orient>
                  </object>
                </object>
                <label>Upload</label>
                <orient>wxVERTICAL</orient>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <object class="spacer">
                  <option>1</option>
                </object>
                <object class="sizeritem">
                  <object class="wxButton" name="CloseButton">
                    <label>Close</label>
                    <XRCED>
                      <events>EVT_BUTTON</events>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                </object>
                <object class="spacer">
                  <option>1</option>
                </object>
                <object class="sizeritem">
                  <object class="wxButton" name="UPLOAD">
                    <label>Upload</label>
                    <XRCED>
                      <events>EVT_BUTTON</events>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>0</option>
                  <flag>wxLEFT|wxRIGHT</flag>
                  <border>3</border>
                </object>
                <object class="spacer">
                  <option>1</option>
                </object>
                <orient>wxHORIZONTAL</orient>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>300,10</size>
              <option>1</option>
              <flag>wxALL|wxEXPAND</flag>
            </object>
          </object>
        </object>
        <option>2</option>
        <flag>wxALL|wxEXPAND|wxADJUST_MINSIZE</flag>
        <border>0</border>
      </object>
    </object>
    <title>Upload Tiles</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/DyMaps/DyMaps_xrc', DyMaps_xrc)
    __res.Load('memory:XRC/DyMaps/DyMaps_xrc')

